@startuml
'https://plantuml.com/use-case-diagram

left to right direction
skinparam packageStyle rect
actor Пользователь as User
actor :Научный руководитель: as SPK
SPK -> User

rectangle ECG-Digtz {
    User --> (Оцифровать)
    SPK --> (Выгрузить все оцифрованные снимки)
    (Оцифровать) .> (Выгрузить) : include
}

@enduml